version: '2'
services:
    reverseproxy:
        image: reverseproxy
        ports:
            - 8081:8080
        restart: always
 
    nginx:
        depends_on:
            - reverseproxy
        image: nginx:alpine
        restart: always
 
    node:
        depends_on:
            - reverseproxy
        image: jcaluk1/node-web-app-cities
        ports:
            - 8083:8888
        restart: always
    
    bulletin:
        depends_on:
            - reverseproxy
        image: kenan/bulletin:latest
        ports:
            - 8085:8082
        restart: always